version: '3.4'

networks:
 kong-net:
  driver: bridge

services:
  kong-database:
    image: postgres:9.6
    networks: 
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports: 
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql  

  #######################################
  # Kong database migration
  #######################################
  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    networks:
      - kong-net
    restart: on-failure

  ######################################
  #Kong: The API Gateway
  ######################################
  kong:
    image: kong:latest
    #restart: always
    
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./.docker/kong:/home/kong
      - ./.docker/kong/config:/etc/kong  
    ports:
      - "8001:8001"
      - "80:8000"
    depends_on: 
      - kong-database  

  server:
    image: server
    build: ./.docker/server
    command: yarn start:dev
    ports: 
      - 3000:80
    volumes:
      - ./server:/usr/src/server
    networks:
      - kong-net

  client:
    image: client
    build: ./.docker/client
    command: yarn start:dev
    ports: 
      - 3001:80
    networks:
      - kong-net
    volumes:
      - ./client:/usr/src/client

